sonar.projectKey=Mar-Tini_smart-subscription2
sonar.organization=mar-tini

# Sources et exclusions
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,.github/**,*.config.js

# Couverture
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js

# Langage
sonar.language=js

# Encodage
sonar.sourceEncoding=UTF-8