sonar.projectKey=Mar-Tini_smart-subscription2
sonar.organization=mar-tini

# Sources
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.language=js

# Couverture
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js

# Exclusions
sonar.exclusions=node_modules/**,coverage/**,.github/**,**/*.test.js,**/*.spec.js,**/*.config.js,**/*.min.js,jest.config.js,babel.config.js,webpack.config.js,.eslintrc.js,**/__mocks__/**,**/fixtures/**,**/dist/**,**/build/**